exports.handler = async (event, context) => {
  
  // CONFIGURATION
  const numVariables = 1;
  const responseFormat = "˚₊✧ {var1}";
  
  // AFFIRMATIONS
  const variable1 = [
    "you don't need to earn rest. you're allowed to have it.",
    "it's okay to be learning instead of already knowing.",
    "you are allowed to take up space, even quietly.",
    "not everything needs to be figured out today.",
    "your pace is valid, even when it's slower than others.",
    "you are not behind. you are on your own timeline.",
    "it's okay if today looks different than you planned.",
    "you're allowed to change your mind.",
    "you don't need to explain yourself to be valid.",
    "you are doing the best you can with what you have right now.",
    "progress still counts when it's small.",
    "you're allowed to take breaks without quitting.",
    "it's okay to need help sometimes.",
    "your feelings make sense, even if they're messy.",
    "you don't have to be productive to be worthy.",
    "you are allowed to rest without guilt.",
    "you can be kind to yourself and still grow.",
    "you don't need permission to care about the small things.",
    "if it matters to you, it matters. period.",
    "you're allowed to protect your peace.",
    "it's okay to go at a pace that feels safe for you.",
    "you're not weak for feeling things deeply.",
    "you are allowed to start again. and again, and again. as many times as you need.",
    "your effort matters, even when the outcome is unexpected.",
    "you don't have to have everything together to be respected.",
    "it's okay if you're still figuring out who you are.",
    "you are more than your most recent mistake.",
    "you are more than your biggest mistake.",
    "you're allowed to take things one step at a time.",
    "you don't owe anyone constant access to you.",
    "it's okay to need reassurance.",
    "you're allowed to be proud of yourself!",
    "you don't have to rush healing.",
    "your curiosity is a strength.",
    "it's okay to rest before you're exhausted.",
    "you are allowed to set boundaries without guilt.",
    "your voice matters, even when it shakes.",
    "you don't need to compare your journey to anyone else's.",
    "it's okay to want things just because they matter to you.",
    "you're allowed to let go of what's not working.",
    "you don't need to be perfect to be enough.",
    "your presence has value.",
    "it's okay if you're quieter today.",
    "you're allowed to take happiness seriously.",
    "you don't have to prove your pain to deserve care.",
    "your thoughts are worth listening to.",
    "it's okay to do things imperfectly.",
    "you're allowed to trust yourself more.",
    "you don't need to have a five-year plan to move forward to tomorrow.",
    "it's okay to rest even when others are busy.",
    "your boundaries are a form of self-respect.",
    "you are allowed to exist without performing.",
    "you don't have to be useful all the time.",
    "it's okay if your best looks different each day.",
    "you are allowed to take up emotional space.",
    "you don't need to minimize yourself to belong.",
    "your effort is appreciated, even when it feels invisible.",
    "it's okay to slow down and check in with yourself.",
    "you're allowed to want more and still be grateful.",
    "you don't have to justify your needs.",
    "your growth doesn't have to be loud to be real.",
    "it's okay to choose peace over proving a point.",
    "you are allowed to be a work in progress.",
    "you don't need to have all the answers right now.",
    "your emotions are information, not a failure.",
    "it's okay to take a pause before responding.",
    "you're allowed to protect what matters to you.",
    "you don't have to meet every expectation placed on you.",
    "your kindness counts, even when it's small.",
    "it's okay to need time.",
    "you are allowed to exist at your own volume.",
    "you don't have to be okay all the time.",
    "your experiences are real and valid.",
    "it's okay to let today be \"good enough.\"",
    "you're allowed to choose yourself.",
    "you don't need to rush clarity.",
    "it's okay to take things personally sometimes. you're human.",
    "you're allowed to be soft and strong at the same time.",
    "you don't have to carry everything alone.",
    "your needs are not a burden.",
    "it's okay to rest in the middle of becoming yourself.",
    "you are allowed to say no without explanation.",
    "you don't need to shrink to make others comfortable.",
    "your healing is not on a deadline.",
    "it's okay to start small.",
    "you're allowed to trust the process, even when it makes no sense.",
    "you don't have to be fearless to move forward.",
    "your boundaries teach people how to treat you.",
    "it's okay if you're still learning how to be kind to yourself.",
    "you're allowed to take this seriously.",
    "you don't need to rush through your feelings.",
    "your effort matters on hard days, easy days, and all days in-between.",
    "it's okay to be proud of surviving something difficult.",
    "you're allowed to exist without explanation.",
    "you don't have to do everything today.",
    "your time and energy are valuable.",
    "it's okay to ask for what you need.",
    "you're allowed to move forward slowly.",
    "you don't need to try to be extraordinary to matter.",
    "it's okay to be exactly where you are right now."
  ];
  
  // Random selection
  const random1 = variable1[Math.floor(Math.random() * variable1.length)];
  const response = responseFormat.replace("{var1}", random1);
  
  return {
    statusCode: 200,
    body: response
  };
};
